name: Go CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'  # Specify your Go version

      - name: Install dependencies
        run: go mod tidy

      - name: Install X11 development libraries (Linux only)
        if: matrix.os == 'ubuntu-latest'
        run: |
            sudo apt update
            sudo apt install xorg       

      - name: Run tests
        run: go test ./...  # Run all tests

  release:
    runs-on: ${{ matrix.os }}
    needs: test
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        arch: [amd64, arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Build project
        run: |
          GOOS=${{ matrix.os == 'windows-latest' && 'windows' || matrix.os == 'macos-latest' && 'darwin' || 'linux' }}
          GOARCH=${{ matrix.arch }}
          go build -o myapp-${{ matrix.os }}-${{ matrix.arch }} ./...  # Adjust the output name as needed

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v0.0.1
          files: |
            odt-${{ matrix.os }}-${{ matrix.arch }}  # Adjust the path to your binaries
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
